connection: 
  host: irc.freenode.net
  port: 6667
  secure: false
login: 
  nickname: 'nodetip'
  username: 'nodetip'
  realname: node.js dogecoin tipping bot
channels: 
  - '##tipbots'
rpc:
  host: localhost
  port: 22555
  user: dogecoinrpc
  pass: pass
  master_account: unek
coin:
  withdrawal_fee: 2
  min_withdraw: 5
  min_confirmations: 3
  short_name: ' DOGE'
  full_name: dogecoin
messages:
  error: 'Sorry %name%, something went wrong.'
  no_funds: "Sorry %name%, you don't have enough funds (you're %short% %short_name% short)"
  not_identified: '%name%: You need to be identified with NickServ to tip.'
  tipped: 'Wow! %from% tipped %to% %amount%%short_name%! "/msg %nick% help" to claim.'
  balance: '%name% has %balance%%short_name%.'
  balance_unconfirmed: '%name% has %balance%%short_name% (unconfirmed: %unconfirmed%%short_name%)'
  deposit_address: "%name%'s deposit address is %address%"
  withdraw_too_small: 'Sorry %name%, you need to withdraw at least %min_withdraw%%short_name% (you have %balance%%short_name%)'
  invalid_address: 'Sorry %name%, the address you specified is invalid (%address%).'
  withdraw_success: '%name%: %amount%%short_name% has been withdrawn from your account to %address%'
  withdraw_success2: 'You have been charged %withdrawal_fee%%short_name% withdrawal fee. Transaction id: %transaction%.'